# Generated by Django 5.2.4 on 2025-07-28 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category_image', models.ImageField(blank=True, null=True, upload_to='categories')),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
            },
        ),
        migrations.AlterModelOptions(
            name='telegramuser',
            options={'verbose_name': 'Telegram Foydalanuvchi', 'verbose_name_plural': 'Telegram Foydalanuvchilar'},
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_1', models.CharField(max_length=100)),
                ('name_2', models.CharField(max_length=100)),
                ('guest_name', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('wedding_hall', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('apartment', models.CharField(blank=True, max_length=100, null=True)),
                ('unique_url', models.CharField(default='0Lc4JGymSS', max_length=100, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.telegramuser')),
            ],
            options={
                'verbose_name': 'Taklifnoma',
                'verbose_name_plural': 'Taklifnomalar',
            },
        ),
    ]
