# Generated by Django 5.2.4 on 2025-07-28 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_category_alter_telegramuser_options_invitation'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='backgrounds')),
            ],
            options={
                'verbose_name': 'Fon rasmi',
                'verbose_name_plural': 'Fon rasmlari',
            },
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='guest_name',
        ),
        migrations.AlterField(
            model_name='invitation',
            name='name_2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='unique_url',
            field=models.CharField(default='3GlfO7UaTB', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='invitation',
            name='background',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.backgroundimage'),
        ),
    ]
