# Generated by Django 5.2.4 on 2025-07-28 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_backgroundimage_remove_invitation_guest_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='unique_url',
            field=models.CharField(default='XlDfBUQa4Y', max_length=100, unique=True),
        ),
    ]
