# Generated by Django 5.2.4 on 2025-07-28 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_invitation_unique_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='unique_url',
            field=models.CharField(default='icHT0fzjQz', max_length=100, unique=True),
        ),
    ]
